#FROM python:3.8-slim-buster

# Imagem base 
FROM python:3.8-slim-buster

# Autor
LABEL Author="Jose Cabicho" Email="jcabicho@gmail.com" 

#Diretório de trabalho no container
WORKDIR /app

# Copiando os nomes dos pacotes a serem instalados.
COPY requirements.txt . 

# Instalando pacotes e dependências.
RUN pip install -r requirements.txt

# Copiando projeto.
COPY src/ /app # . /app

# Expondo porta 5000
EXPOSE 5000

# Comando de execução do container.
CMD ["gunicorn", "--workers=3", "--bind", "0.0.0.0:5000", "-c", "config.py", "app:app"]
