name: CI-CD

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Docker Login
        
        uses: docker/login-action@v1.14.1
        with:
          username: ${{secret.DOCKERHUB_USER}} # optional
          # Password or personal access token used to log against the Docker registry
          password: ${{secret.DOCKERHUB_USER}} # ${{ # optional
          # Specifies whether the given registry is ECR (auto, true or false)
          #ecr: # optional, default is autoUB
          # Log out from the Docker registry at the end of a job
          #logout: # optional, default is true
        # Runs a single command using the runners shell
        #- name: Docker Login
        #  uses:
        #  run: echo Hello, world!

